package.json, src/index.js, test/integration.js, yarn.lock
As the `README.md` file states it, we're allowing the `createReadStream` handler to be a promise or asynchronous function (when loading something for a third party source in there, for example).
=> Added support for async `createReadStream`

README.md, src/index.js, test/fixtures/special-directory/not-an-index.md, test/integration.js
- We've decided that `cleanUrls` should default to `true` (as literally everyone will use that option).
- We're not matching against `/index` for cleaning URLs anymore, because paths could also end with `/index.js`, so we added a `$` for ensuring it's the end of the path.
💅
=> Applied improvements from another round of testing

README.md
This explains which paths can contain path segments or regular expressions (matched with [path-to-regexp](https://github.com/pillarjs/path-to-regexp) or globs (matched with [minimatch](https://github.com/isaacs/minimatch)).
We're using [minimatch](https://github.com/isaacs/minimatch) for compatibility with [superstatic](https://github.com/firebase/superstatic).
=> Precisely document potential value for paths

src/index.js
BEFORE
AFTER
I also fixed the metadata that the user receives when the `Accept` header contains `application/json`.
=> Render correct icon for parent path

src/index.js, test/integration.js
In some case, the `content-type` response return for serve is `null`
For example when using **serve** with  `--single` flag, the content-type of `/whatever` would be null instead of `text/html`
This pull request fixes just that.
=> Fall mime type back to the one of the rewritten path

README.md, package.json, src/index.js, test/integration.js, yarn.lock
This will prevent things like `../../bla` in the URL.
=>  Prevent path traversal vulnerabilities

package.json, src/index.js, yarn.lock
This PR adds a new feature to the package: A default for the `Content-Disposition` header, which is responsible for deciding whether an asset should be downloaded or displayed within the browser.
We never had this in `serve` before, but since our static deployments on Now are also sending this header, we need it to become fully compatible. Aside from that, it's just a great default to have and can be overridden at any time using the `headers` config property.
=> Added default `Content-Disposition` header

README.md
Hi,
I've spotted a small mismatch in README.md documentation - it mentions that option `public` is of type Boolean, while in example it is a String.
=> Update README.md to fix 'public' option data type

README.md, src/index.js, test/integration.js
This is necessary as we need the library to make less stat calls for production. Aside from that `.htm` is just a very odd extension that most people don't use (there's also no good reason to not use `.html`).
=> Make `cleanUrls` stop stripping `.htm` extension

src/index.js, test/integration.js
Previously, the package was firstly checking the existence of the requested path and then seeing if related paths like `<path>/index.html` exist.
However, since directory listings are not the most common use case of this package (but rather rendering files and static projects), I decided to move this further down the line.
As a result, if you request `/`, the first `stat` call will no more be for the directory `/`, but rather for `/index.html`, as long as `cleanUrls` or a respective `rewrites` item is enabled.
---
🎉 **This is not a breaking change, it only reduces the number of `stat` calls to be made until a file is reached and sent back to the client.**
🍏  **I also added 4 more tests, in addition to the existing ones passing. We now have 43!**
=> Reduce number of stat calls

README.md, src/index.js, test/fixtures/single-directory/content.txt, test/integration.js
As described in [the readme](https://github.com/zeit/serve-handler/tree/render-single#rendersingle-boolean), this new property will allow for rendering a file if the directory you're trying to access only contains one single file.
For example: If you have a directory called `/test` with `image.png` inside, then you will see `image.png` be rendered in your browser if you access `/test`.
---
This property is very similar to `cleanUrls`, yet very distinct: It doesn't try to `stat` upfront, but only considers the contents of directories that have been loaded.
I also added a test for this functionality, so we have 46 tests now.
=> Added `renderSingle` configuration property

src/index.js, test/integration.js
Previously, an empty `Location` header was passed. This is now fixed!
This closes https://github.com/zeit/serve/issues/402.
=> Fixed requests to `/index` being redirected wrong

src/index.js, test/fixtures/public-folder.test/index.html, test/integration.js
This fixes https://github.com/zeit/serve/issues/421.
This passes all tests.
It will still have problems with filenames that have no extension, but it addresses not allowing dots in the "public" folder setting.
=> Allow dots in value of `public` option

src/index.js, test/integration.js
Previously, requests like `/%E0%A4%A` caused a 500 instead of a 400:
```
{ URIError: URI malformed
at decodeURIComponent (<anonymous>)
at module.exports (/usr/src/app/node_modules/serve-handler/src/index.js:493:23)
at trackStatusCodes (/usr/src/app/src/index.js:143:40)
at /usr/src/app/node_modules/@zeit/metrics/http-status.js:20:10
at module.exports.apiErrors (/usr/src/app/src/index.js:248:5)
at <anonymous>
[stack]: 'URIError: URI malformed\n    at decodeURIComponent (<anonymous>)\n    at module.exports (/usr/src/app/node_modules/serve-handler/src/index.js:493:23)\n    at trackStatusCodes (/usr/src/app/src/index.js:143:40)\n    at /usr/src/app/node_modules/@zeit/metrics/http-status.js:20:10\n    at module.exports.apiErrors (/usr/src/app/src/index.js:248:5)\n    at <anonymous>',
[message]: …
```
=> Properly handle requests with malformed URIs

src/index.js, test/integration.js
Previously, custom headers were not applied to all error responses, only for `.html` pages.
Once this is merged, they will also be applied to the default error renderings.
=> Allow custom headers to be set for default error responses

README.md, src/index.js
This allows send-handler to be combined with other servers (such as the
Next.js server) to provide a custom handler for unknown paths.
=> Support `sendError` as middleware

README.md, src/index.js, test/integration.js
This adds native support for `304` responses for any path in the case that:
- A `ETag` header was set for that path
- A request comes in to that path with `If-None-Match` matching the previously sent `ETag`
Only if both are true, the `304` response will occur.
=> Handle `ETag` and `If-None-Match`

README.md
This ensures we're linking to the ZEIT community, which is now the main one.
=> Updated link of Spectrum badge

README.md, package.json, src/index.js, test/integration.js, yarn.lock
I hope this isn't considered out of scope...
This can be tested in the "real world" by browsing to a video file in Safari (didn't work before)
Should these features be implemented as well?
- Handling of multiple ranges (with a multipart response, currently only the first range is used)
- the `If-Range` header
This change could be considered breaking:
```diff
--- a/test/integration.js
+++ b/test/integration.js
@@ -869,9 +869,9 @@ test('set `createReadStream` handler to async function', async t => {
// eslint-disable-next-line no-undefined
const url = await getUrl(undefined, {
-               createReadStream: async file => {
+               createReadStream: async (file, opts) => {
await sleep(2000);
-                       return fs.createReadStream(file);
+                       return …
```
=> Range request handling

src/index.js, test/integration.js
In https://github.com/zeit/serve-handler/pull/40, we introduced support for HTTP range requests.
With this PR right here, we're making sure to only try retrieving a the range of a file if the `stat` call returns the `size` of the file.
If it doesn't, we need to fall back to sending the full file, not an error.
=> Only try range if size is accessible

README.md
Removes an extraneous `}` from the `headers` example configuration.
=> Fix `headers` example JSON

src/index.js, test/integration.js
The coverage decreased in https://github.com/zeit/serve-handler/pull/56, this PR brings it back to 100%.
But most importantly, if an error occurs while reading an error template, we don't try to read the error template again, but instead just render the default text error.
=> Prevent errors from causing a crash loop

README.md, package.json, src/glob-slash.js, src/index.js, test/integration.js, yarn.lock
We should use Posix for path normalization (a.k.a. slasher).
Currently, we are using `glob-slash`. But the project has not been maintained for the last 4 years, I think it make sense to make part of the code to `serve-handler` and we fix it here.
This will fix #59 since `redirects` and `rewrites` are essentially not working at all on Windows.
=> Fix #59 Use Posix for slasher

src/index.js
Since we are decoding all incoming request paths [here](https://github.com/zeit/serve-handler/blob/22d4b00366a0d6776153352504262cd6bd5f393d/src/index.js#L533), we need to encode them again, in order to prevent Node.js from throwing an error when trying to send invalid headers.
=> Encode redirection targets properly

README.md, src/index.js, test/fixtures/symlinks/package.json, test/integration.js
In order to prevent potential security issues, the team has decided to disable symlinks by default.
To enable them, you can define the `symlinks` option:
```js
{
"symlinks": true
}
```
Furthermore, this pull request also adds a new handler for `fs.realpath`, which is responsible for resolving the target of symlinks if they are enabled.
=> Disable symlinks by default

README.md
This statement is not correct anymore:
> and static deployments running on [Now](https://zeit.co/now).
Nowadays, you would use a [static Builder](https://zeit.co/docs/v2/deployments/official-builders/static-now-static/).
=> Removed faulty description

src/index.js
Resolves https://github.com/zeit/serve/issues/525
`path.resolve('/some-url')` returns `C:\\some-url` in Windows. Which breaks rewrites and makes the serve `--single` option not work in windows.
Using path.posix gives us linux/unix/posix functionality for resolving the path, which preserves the security fix that was added in https://github.com/zeit/serve-handler/pull/76 while still working in Windows.
I have verified that the `--single` option works with my changes, in both Windows 10 and Mac.
=> Using posix path resolution. Resolves serve issue #525

src/index.js
Fixes error described in #80. See issue for problem description.
Resolves #80
=> Fix issue with file in path

src/index.js, test/fixtures/docs.txt, test/integration.js
This is so that an index file that has its file extension changed is properly invalidated by the browser so that the changed `Content-Type` header is respected.
=> Include file path in `ETag` header generation

package.json, yarn.lock
=> Bump minimatch from 3.0.4 to 3.1.2

.github/workflows/publish.yaml
We need to use `published` instead of `created` since drafts will never get into the `created` state.
Also added `workflow_dispatch` to manually run it again.
See the docs https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
=> Fix publish action

.github/workflows/publish.yaml, .github/workflows/tests.yaml, package.json
I've forgot to include `npm run prepublish` in the publish action.
Due to this mistake, some files were not included in the 6.1.4 release.
=> Ensure `npm run prepublish` gets executed

README.md
Removed the CircleCI badge earlier when moving to GitHub Actions.
This PR adds an updated badge.
=> Add Tests Badge back to Readme

README.md
Twitter was renamed to X and my X handle changed from `@notquiteleo` to `@leo`.
This change replaces the previous broken link with the new working link.
=> X handle has changed

package.json, src/index.js
=> feat: replace the 'fast-url-parser' module with the 'node:url' module

.github/workflows/tests.yaml, jest.config.js, package.json, src/glob-slash.js, src/index.js, test/integration.test.js, yarn.lock
- Moves tests from `ava` to `jest`
- Replaces the code coverage reporting from `nyc` with the built in reporting from `jest`
=> Move tests and reporting to `jest`

package.json, src/glob-slash.js, src/index.js, test/integration.test.js, yarn.lock
Thanks to @alana-cruickshank for the original PR with those changes https://github.com/vercel/serve-handler/pull/215
Closes https://github.com/vercel/serve-handler/issues/211
Closes https://github.com/vercel/serve-handler/issues/212
Removes the `node:` I've accidentally added in https://github.com/vercel/serve-handler/pull/216
=> Bump `path-to-regexp` to `3.3.0`
